spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: yinfan_goods_route
#          uri: http://localhost:18081
          uri: lb://goods

          predicates:
#            - Host=sell.com** #hoshost匹配
            - Path=/**
          filters:
#          - StripPrefix=1
#            - PrefixPath=/band
#      routes:
#        - id: changgou_goods_route
#          uri: lb://goods
#          predicates:
#            - Path=/api/goods/**
#          filters:
#            - StripPrefix=1
#            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory,局部限流过滤器
#              args:
#                #用户唯一识别标识符
#                key-resolver: "#{@ipKeyResolver}"
#                #每秒允许一个请求
#                redis-rate-limiter.replenishRate: 10
#                #允许并发4个请求
#                redis-rate-limiter.burstCapacity: 4
#        #用户微服务
#        - id: changgou_user_route
#          uri: lb://user
#          predicates:
#            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
#          filters:
#            - StripPrefix=1
#        #订单微服务
#        - id: changgou_order_route
#          uri: lb://order
#          predicates:
#            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
#          filters:
#            - StripPrefix=1
#
  application:
    name: gateway-web
#  #Redis配置
#  redis:
#    host: 192.168.177.59
#    port: 6379

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true