server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/kyle826/yinfan-config.git
          force-pull: true
          username: 79412906@qq.com
          password: 79412906zhang
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
